### ISSUE TITLE
How to get the problems?

### ISSUE THREAD

**Issue by rockneurotiko** [exercism/xpony#3]
Sorry for this probably noob question, but I can't fetch the `hello-world` problem..

I have the exercism version 2.2.0, and I'm trying to fetch the problem with:

```
$ exercism fetch pony hello-world     
2015/07/21 20:53:09 unable to fetch problems (HTTP: 404) - We don't have problem 'hello-world' in 'pony'
```

Thanks!!

**Comment by canweriotnow** [comment]
@rockneurotiko It's too early to be available via the exercism binary, even as an inactive - still needs docs, etc, and to be added as a submodule to the tracks list (See #1). I'll try to get it into a state where it can at least be added to inactive tracks ASAP, but I'm kinda building this track as a way of learning Pony myself, so no promises :smiley_cat:

**Comment by rockneurotiko** [comment]
Ou... I thinked that you can download the tracks inactives manually :smile:
I'll try to help you with the problems, but I'm learning Pony too, so no promises neither ;-)
Thanks for add this track!

**Comment by canweriotnow** [comment]
You can download the inactives manually, once they're added to the main collection... this repo was created yesterday, so it's not there yet.

But please, send PRs!!!

**Comment by kytrinyx** [comment]
I'll get this added to the main repo tonight (still inactivated, but you'll be able to fetch the individual problems).

**Comment by canweriotnow** [comment]
@rockneurotiko confirming `exercism fetch pony hello-world` is now available for your enjoyment.

**Comment by kytrinyx** [comment]
The api is updated, `exercism fetch pony hello-world` should now work.

**Comment by rockneurotiko** [comment]
yeah, it works, thanks! :heart:
